// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiORMVk4o61iS4HCx6EHelZHsvEnfCCIc',
    appId: '1:331703055472:web:05fa428cea8d5ac58030b5',
    messagingSenderId: '331703055472',
    projectId: 'clothing-18102',
    authDomain: 'clothing-18102.firebaseapp.com',
    databaseURL: 'https://clothing-18102-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-18102.firebasestorage.app',
    measurementId: 'G-T6231CP01G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhn1rjwoGXlqdMYM3oK1wyeUofr9-22zc',
    appId: '1:331703055472:android:a9f3e2b569d9a83c8030b5',
    messagingSenderId: '331703055472',
    projectId: 'clothing-18102',
    databaseURL: 'https://clothing-18102-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-18102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr6mec6uZR7p9nhCmsZwgD9XDql7Gdrdg',
    appId: '1:331703055472:ios:c248e93237deba568030b5',
    messagingSenderId: '331703055472',
    projectId: 'clothing-18102',
    databaseURL: 'https://clothing-18102-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-18102.firebasestorage.app',
    androidClientId: '331703055472-n3ol0jfgu2mqksefi2j5pias1notafpc.apps.googleusercontent.com',
    iosClientId: '331703055472-klee54n5qak3viags23ib6qf9nknlkm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr6mec6uZR7p9nhCmsZwgD9XDql7Gdrdg',
    appId: '1:331703055472:ios:c248e93237deba568030b5',
    messagingSenderId: '331703055472',
    projectId: 'clothing-18102',
    databaseURL: 'https://clothing-18102-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-18102.firebasestorage.app',
    androidClientId: '331703055472-n3ol0jfgu2mqksefi2j5pias1notafpc.apps.googleusercontent.com',
    iosClientId: '331703055472-klee54n5qak3viags23ib6qf9nknlkm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiORMVk4o61iS4HCx6EHelZHsvEnfCCIc',
    appId: '1:331703055472:web:9386a5b746b7c37c8030b5',
    messagingSenderId: '331703055472',
    projectId: 'clothing-18102',
    authDomain: 'clothing-18102.firebaseapp.com',
    databaseURL: 'https://clothing-18102-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-18102.firebasestorage.app',
    measurementId: 'G-1KCNEL4KK5',
  );
}
